from pathlib import Path

path = Path('notion-ide/worker/src/ui.js')
text = path.read_text(encoding='utf-8')

old_connect = '''async function connect(){showError();config=await api("/api/bootstrap",{method:"POST"});sessionStorage.setItem("notionIdeKey",$("key").value);$("connection").textContent="connected";$("branchLabel").textContent=config.branch;loadedDirs.clear();$("tree").innerHTML="";await mountRoot();updateRunButton()}'''
new_connect = '''async function connect(){showError();config=await api("/api/bootstrap",{method:"POST"});sessionStorage.setItem("notionIdeKey",$("key").value);$("connection").textContent="connected";$("branchLabel").textContent=config.branch;loadedDirs.clear();$("tree").innerHTML="";await mountRoot();await restoreRunSession();updateRunButton()}'''

old_command = '''function pythonCommand(entrypoint){return entrypoint.endsWith(".py")?"python "+entrypoint:"python -m "+entrypoint}'''
new_command = '''async function pythonCommand(entrypoint){const python=".venv/bin/python";if(!entrypoint.endsWith(".py"))return python+" -m "+entrypoint;const slash=entrypoint.lastIndexOf("/");if(slash<0)return python+" "+entrypoint;const packageDir=entrypoint.slice(0,slash);let current="";for(const part of packageDir.split("/")){current=current?current+"/"+part:part;try{await api("/api/file?path="+encodeURIComponent(current+"/__init__.py"))}catch{return python+" "+entrypoint}}return python+" -m "+entrypoint.slice(0,-3).replaceAll("/",".")}
const RUN_SESSION_KEY="notionIdeActiveRun";
function persistRunSession(){if(!runCommit)return;localStorage.setItem(RUN_SESSION_KEY,JSON.stringify({runCommit,runId,jobId,lastRunCommand,cancelRequested}))}
function clearRunSession(){localStorage.removeItem(RUN_SESSION_KEY)}
async function restoreRunSession(){let saved=null;try{saved=JSON.parse(localStorage.getItem(RUN_SESSION_KEY)||"null")}catch{clearRunSession();return}if(!saved?.runCommit)return;runCommit=saved.runCommit;runId=saved.runId||null;jobId=saved.jobId||null;lastRunCommand=saved.lastRunCommand||"";cancelRequested=Boolean(saved.cancelRequested);$("terminalCommand").textContent=lastRunCommand?"$ "+lastRunCommand:"restoring run";setRunState("WAITING_FOR_RUN");setTerminal((lastRunCommand?"$ "+lastRunCommand+"\\n\\n":"")+"STATE: RESTORING\\nReattaching to previous GitHub Actions run...");if(pollTimer)clearTimeout(pollTimer);await pollRun()}'''

old_run = '''async function run(){showError();const entrypoint=currentEntrypoint();if(currentBuffer()?.dirty)await saveFile();lastRunCommand=pythonCommand(entrypoint);runCommit=null;runId=null;jobId=null;cancelRequested=false;$("terminalCommand").textContent="$ "+lastRunCommand;$("runLink").textContent="";$("artifactLinks").textContent="";$("loadLog").disabled=true;$("cancelRun").disabled=true;setRunState("REQUESTING");updateRunButton();setTerminal("$ "+lastRunCommand+"\\n\\nSTATE: REQUESTING\\nCreating run request commit...");const d=await api("/api/run",{method:"POST",body:JSON.stringify({entrypoint})});runCommit=d.commit_sha;setRunState("WAITING_FOR_RUN");setTerminal("$ "+lastRunCommand+"\\n\\nSTATE: WAITING_FOR_RUN\\nRun request committed: "+runCommit.slice(0,8)+"\\nWaiting for GitHub Actions to create the workflow run...");if(pollTimer)clearTimeout(pollTimer);await pollRun()}'''
new_run = '''async function run(){showError();const entrypoint=currentEntrypoint();if(currentBuffer()?.dirty)await saveFile();lastRunCommand=await pythonCommand(entrypoint);runCommit=null;runId=null;jobId=null;cancelRequested=false;$("terminalCommand").textContent="$ "+lastRunCommand;$("runLink").textContent="";$("artifactLinks").textContent="";$("loadLog").disabled=true;$("cancelRun").disabled=true;setRunState("REQUESTING");updateRunButton();setTerminal("$ "+lastRunCommand+"\\n\\nSTATE: REQUESTING\\nCreating run request commit...");const d=await api("/api/run",{method:"POST",body:JSON.stringify({entrypoint})});runCommit=d.commit_sha;persistRunSession();setRunState("WAITING_FOR_RUN");setTerminal("$ "+lastRunCommand+"\\n\\nSTATE: WAITING_FOR_RUN\\nRun request committed: "+runCommit.slice(0,8)+"\\nWaiting for GitHub Actions to create the workflow run...");if(pollTimer)clearTimeout(pollTimer);await pollRun()}'''

old_poll = '''async function pollRun(){if(!runCommit)return;try{const d=await api("/api/run-status?sha="+encodeURIComponent(runCommit));if(!d.found){setRunState("WAITING_FOR_RUN");setTerminal("$ "+lastRunCommand+"\\n\\nSTATE: WAITING_FOR_RUN\\nRequest commit: "+runCommit.slice(0,8)+"\\nGitHub Actions has not created the run yet.");updateRunButton();pollTimer=setTimeout(pollRun,3000);return}runId=d.run.id;jobId=d.jobs[0]?.id||null;const actual=lifecycleFromRun(d.run);const state=cancelRequested&&d.run.status!=="completed"?"CANCEL_REQUESTED · "+actual:actual;setRunState(state);$("runLink").innerHTML="<a target='_blank' rel='noreferrer' href='"+d.run.html_url+"'>run "+d.run.id+"</a>";const steps=terminalSteps(d);setTerminal("$ "+lastRunCommand+"\\n\\nSTATE: "+state+"\\nGitHub status: "+d.run.status+(d.run.conclusion?" / "+d.run.conclusion:"")+(steps?"\\n\\n"+steps:""));updateRunButton();if(d.run.status!=="completed"){pollTimer=setTimeout(pollRun,3000)}else{$("cancelRun").disabled=true;$("loadLog").disabled=!jobId;await loadArtifacts();if(jobId)await loadLog();updateRunButton()}}catch(e){setRunState("IDE_ERROR");appendTerminal("[IDE ERROR] "+friendlyError(e)+"\\n[RETRYING] status check in 7 seconds");updateRunButton();pollTimer=setTimeout(pollRun,7000)}}'''
new_poll = '''async function pollRun(){if(!runCommit)return;try{const d=await api("/api/run-status?sha="+encodeURIComponent(runCommit));if(!d.found){setRunState("WAITING_FOR_RUN");persistRunSession();setTerminal("$ "+lastRunCommand+"\\n\\nSTATE: WAITING_FOR_RUN\\nRequest commit: "+runCommit.slice(0,8)+"\\nGitHub Actions has not created the run yet.");updateRunButton();pollTimer=setTimeout(pollRun,3000);return}runId=d.run.id;jobId=d.jobs[0]?.id||null;persistRunSession();const actual=lifecycleFromRun(d.run);const state=cancelRequested&&d.run.status!=="completed"?"CANCEL_REQUESTED · "+actual:actual;setRunState(state);$("runLink").innerHTML="<a target='_blank' rel='noreferrer' href='"+d.run.html_url+"'>run "+d.run.id+"</a>";const steps=terminalSteps(d);setTerminal("$ "+lastRunCommand+"\\n\\nSTATE: "+state+"\\nGitHub status: "+d.run.status+(d.run.conclusion?" / "+d.run.conclusion:"")+(steps?"\\n\\n"+steps:""));updateRunButton();if(d.run.status!=="completed"){pollTimer=setTimeout(pollRun,3000)}else{$("cancelRun").disabled=true;$("loadLog").disabled=!jobId;await loadArtifacts();if(jobId)await loadLog();clearRunSession();updateRunButton()}}catch(e){setRunState("IDE_ERROR");appendTerminal("[IDE ERROR] "+friendlyError(e)+"\\n[RETRYING] status check in 7 seconds");updateRunButton();pollTimer=setTimeout(pollRun,7000)}}'''

old_cancel = '''async function cancelRun(){if(!runId)throw new Error("GitHub run has not been created yet");cancelRequested=true;setRunState("CANCEL_REQUESTED");updateRunButton();appendTerminal("[CANCEL_REQUESTED] asking GitHub to stop run "+runId+"...");try{const d=await api("/api/cancel",{method:"POST",body:JSON.stringify({run_id:runId})});appendTerminal("[CANCEL_REQUESTED] request committed: "+d.commit_sha.slice(0,8));if(!pollTimer)pollTimer=setTimeout(pollRun,1000)}catch(e){cancelRequested=false;showError(e);throw e}}'''
new_cancel = '''async function cancelRun(){if(!runId)throw new Error("GitHub run has not been created yet");cancelRequested=true;persistRunSession();setRunState("CANCEL_REQUESTED");updateRunButton();appendTerminal("[CANCEL_REQUESTED] asking GitHub to stop run "+runId+"...");try{const d=await api("/api/cancel",{method:"POST",body:JSON.stringify({run_id:runId})});appendTerminal("[CANCEL_REQUESTED] request committed: "+d.commit_sha.slice(0,8));if(!pollTimer)pollTimer=setTimeout(pollRun,1000)}catch(e){cancelRequested=false;persistRunSession();showError(e);throw e}}'''

replacements = [
    (old_connect, new_connect, 'connect'),
    (old_command, new_command, 'command/session'),
    (old_run, new_run, 'run'),
    (old_poll, new_poll, 'poll'),
    (old_cancel, new_cancel, 'cancel'),
]

for old, new, name in replacements:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{name}: expected exactly one match, found {count}')
    text = text.replace(old, new)

path.write_text(text, encoding='utf-8')
print('patched', path)
